export enum E_Tilemap {
    TILEMAP_MAIN_LEVEL = 'TILEMAP_MAIN_LEVEL',
}

export enum E_TilemapLayer {
    WORLD = 'TILEMAP_LAYER_WORLD',
    PLAYER = 'TILEMAP_LAYER_PLAYER',
    ABOVE_PLAYER = 'TILEMAP_LAYER_ABOVE_PLAYER',
    BELOW_PLAYER = 'TILEMAP_LAYER_BELOW_PLAYER',
}

export enum E_SpawnPoint {
    SPAWN_POINT_PLAYER = 'SPAWN_POINT_PLAYER',
}
